const ROUTES = {
  HOME: "/",
  ITEMS: "/items",
  REGISTER: "/register",
  LOGIN: "/login",
  EDITITEM: "/edititem",
  ITEM: "/item",
  CHECKOUT: "/checkout",
  ADDITEM: "/additem",
  MYITEM: "/myitem",
  FAVORITE: "/favorite",
  PROFILE: "/profile",
  LOGOUT: "/logout",
  USERS: "/users",
  EDITUSERS: "/editusers",
  EDITPROFILE: "/editprofile",
  ABOUT: "/about",
  CONTACT: "/contact",
};
export default ROUTES;
